/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.TestManagerFrame;

/**
 *
 * @author admins
 */
public class ThemMoiTest extends javax.swing.JFrame {

    /**
     * Creates new form ThemMoiTest
     */
    public ThemMoiTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrHinhThuc = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jlbIdTest = new javax.swing.JLabel();
        jlblIdNhanKhau = new javax.swing.JLabel();
        jlblTestTime = new javax.swing.JLabel();
        jlblHinhThuc = new javax.swing.JLabel();
        jlblKetQua = new javax.swing.JLabel();
        jlblCachLy = new javax.swing.JLabel();
        jtfIdTest = new javax.swing.JTextField();
        jtfKetQua = new javax.swing.JTextField();
        jtfCachLy = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        testTimeChooser = new com.toedter.calendar.JDateChooser();
        selectBtn = new javax.swing.JButton();
        tenNguoiTestJtf = new javax.swing.JTextField();
        jrbtnTestNhanh = new javax.swing.JRadioButton();
        jdbtnTestChuan = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbIdTest.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbIdTest.setText("ID Test:");

        jlblIdNhanKhau.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlblIdNhanKhau.setText("Họ và tên:");

        jlblTestTime.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlblTestTime.setText("Thời gian test:");

        jlblHinhThuc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlblHinhThuc.setText("Hình thức:");

        jlblKetQua.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlblKetQua.setText("Kết quả:");

        jlblCachLy.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlblCachLy.setText("Cách ly:");

        btnCancel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCancel.setText("Hủy");

        btnAdd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAdd.setText("Thêm mới");

        selectBtn.setText("Chọn...");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });

        tenNguoiTestJtf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tenNguoiTestJtf.setEnabled(false);
        tenNguoiTestJtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenNguoiTestJtfActionPerformed(evt);
            }
        });

        btnGrHinhThuc.add(jrbtnTestNhanh);
        jrbtnTestNhanh.setText("Test Nhanh");
        jrbtnTestNhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnTestNhanhActionPerformed(evt);
            }
        });

        btnGrHinhThuc.add(jdbtnTestChuan);
        jdbtnTestChuan.setText("Test Chuẩn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbIdTest)
                            .addComponent(jlblIdNhanKhau)
                            .addComponent(jlblTestTime)
                            .addComponent(jlblKetQua)
                            .addComponent(jlblHinhThuc)
                            .addComponent(jlblCachLy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbtnTestNhanh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdbtnTestChuan))
                            .addComponent(tenNguoiTestJtf)
                            .addComponent(testTimeChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(jtfIdTest)
                            .addComponent(jtfKetQua)
                            .addComponent(jtfCachLy))
                        .addGap(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbIdTest)
                    .addComponent(jtfIdTest, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jlblIdNhanKhau))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jlblTestTime))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(selectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tenNguoiTestJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(testTimeChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblHinhThuc)
                            .addComponent(jrbtnTestNhanh)
                            .addComponent(jdbtnTestChuan))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblKetQua))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCachLy, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblCachLy))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnAdd))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        
    }//GEN-LAST:event_selectBtnActionPerformed

    private void tenNguoiTestJtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenNguoiTestJtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenNguoiTestJtfActionPerformed

    private void jrbtnTestNhanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnTestNhanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtnTestNhanhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemMoiTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemMoiTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemMoiTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemMoiTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemMoiTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.ButtonGroup btnGrHinhThuc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jdbtnTestChuan;
    private javax.swing.JLabel jlbIdTest;
    private javax.swing.JLabel jlblCachLy;
    private javax.swing.JLabel jlblHinhThuc;
    private javax.swing.JLabel jlblIdNhanKhau;
    private javax.swing.JLabel jlblKetQua;
    private javax.swing.JLabel jlblTestTime;
    private javax.swing.JRadioButton jrbtnTestNhanh;
    private javax.swing.JTextField jtfCachLy;
    private javax.swing.JTextField jtfIdTest;
    private javax.swing.JTextField jtfKetQua;
    private javax.swing.JButton selectBtn;
    private javax.swing.JTextField tenNguoiTestJtf;
    private com.toedter.calendar.JDateChooser testTimeChooser;
    // End of variables declaration//GEN-END:variables
}
